### ISSUE TITLE
Documentation: Missing reference to /SampleApi/TestTokenProxy/README.md

### ISSUE THREAD

**Issue by joelesli** [NorskHelsenett/HelseID.Samples#29]
The readme page of https://github.com/NorskHelsenett/HelseID.Samples references /TestTokenProxy/README.md but the resource is missing.

https://github.com/NorskHelsenett/HelseID.Samples/blob/master/SampleApi/TestTokenProxy/README.md

**Comment by kennethmyhra** [comment]
Fixed here: https://github.com/NorskHelsenett/HelseID.Samples/commit/373fe8ad15f0c96149d117f87966d21756e685c1
