### ISSUE TITLE
parentOrgno blir ikke nullstilt i test-token tjenesten

### ISSUE THREAD

**Issue by frodegil** [NorskHelsenett/HelseID.Samples#64]
parentOrgNo får en (tilfeldig) verdi selv om vi ber den om å være blank (string.Empty) i request-kallet.
Det går fint å sette den til en spesfikk verdi, bare ikke blank.
Virker som om det er en feil med tjenestens tolkning av string.Empty/null.

**Comment by oyvind-bech** [comment]
Tjenesten vil ikke godta en tom verdi eller nullveredi for dette claimet. For å ikke ta med helseid://claims/client/claims/orgnr_parent i et token, må parameteret clientClaimsParametersGeneration settes til GenerateOnlyFromNonEmptyParameterValues (2) [client-claims settes i kallet til TTT] eller generateNone (0) [ingen client-claims]. Se https://utviklerportal.nhn.no/informasjonstjenester/helseid/tilgang-til-helseid/test-token-tjenesten/docs/test-token-tjenesten_no_nnmd/ for beskrivelse av dette («eit token med spesifikke klient-claims (sett berre dei som er relevante)»)
