### ISSUE TITLE
audience-verdien i test-token tjenesten er hardkodet (i selvbetjeningsportalen)

### ISSUE THREAD

**Issue by frodegil** [NorskHelsenett/HelseID.Samples#65]
Test-token-tjenesten (TTT) setter alltid audience til verdien som Helse-Id klienten er hardkodet til i HelseId-portalen (i test).
Det gjør det vanskelig å bruke test-token tjenesten i automatiserte tester som går mot flere forskjellige NHN-tjeneste API-er.
Nå kan vi kun automatisere tester mot API-et som har audience hardkodet i selvbetjeningsportalen.

Det hadde vært fint om vi kunne satt audience manuelt på samme måte som scope når vi oppretter token-et.

**Comment by oyvind-bech** [comment]
Dette er på plass i TTT nå. Se https://utviklerportal.nhn.no/informasjonstjenester/helseid/tilgang-til-helseid/test-token-tjenesten/docs/test-token-tjenesten_no_nnmd/
